# Databricks notebook source
# MAGIC %md
# MAGIC # mobility Bronze Table
# MAGIC 
# MAGIC The goal of this script is to create mobility Bronze table 
# MAGIC 
# MAGIC The following tables are read:
# MAGIC 
# MAGIC | Table |
# MAGIC | ------ |
# MAGIC | 'https://storage.googleapis.com/covid19-open-data/v3/mobility.csv' |
# MAGIC 
# MAGIC 
# MAGIC The following tables are created:
# MAGIC 
# MAGIC | Tables |
# MAGIC | ------ |
# MAGIC | 'bronze_mobility'|

# COMMAND ----------

import pyspark.sql.types as T
import pyspark.sql.functions as F
import datetime as dt
import os
import logging
import io
from re import sub
debug = False
from delta.tables import *
import pandas

# COMMAND ----------

#General Configuration
bronze_datalake_location = "dbfs:/FileStore/RAJAT/BRONZE/mobility"
checkpoint_path= "dbfs:/FileStore/RAJAT/CONFIG/autoloader_checkpoints/mobility"
raw_table_path = "https://storage.googleapis.com/covid19-open-data/v3/mobility.csv"
table = "bigquery-public-data.covid19_open_data.covid19_open_data"
project_id = "reckitt-training-cloud"
bronze_database = "rajat"
bronze_table_name = "bronze_mobility" 
partition_by = "date"

# COMMAND ----------

# MAGIC %md
# MAGIC ## Read Tables

# COMMAND ----------

schema = T.StructType([
    T.StructField("location_key", T.StringType(), True),                                    
    T.StructField("date", T.DateType(), True),                                  
    T.StructField("place_id", T.StringType(), True),                                    
    T.StructField("wikidata_id", T.StringType(), True),                                     
    T.StructField("datacommons_id", T.StringType(), True),                                  
    T.StructField("country_code", T.StringType(), True),                                    
    T.StructField("country_name", T.StringType(), True),                                    
    T.StructField("iso_3166_1_alpha_2", T.StringType(), True),                                  
    T.StructField("iso_3166_1_alpha_3", T.StringType(), True),                                  
    T.StructField("aggregation_level", T.LongType(), True),                                     
    T.StructField("new_confirmed", T.LongType(), True),                                     
    T.StructField("new_deceased", T.LongType(), True),                                  
    T.StructField("cumulative_confirmed", T.LongType(), True),                                  
    T.StructField("cumulative_deceased", T.LongType(), True),                                   
    T.StructField("cumulative_tested", T.LongType(), True),                                     
    T.StructField("new_persons_vaccinated", T.LongType(), True),                                    
    T.StructField("cumulative_persons_vaccinated", T.LongType(), True),                                     
    T.StructField("new_persons_fully_vaccinated", T.LongType(), True),                                  
    T.StructField("cumulative_persons_fully_vaccinated", T.LongType(), True),                                   
    T.StructField("new_vaccine_doses_administered", T.LongType(), True),                                    
    T.StructField("cumulative_vaccine_doses_administered", T.LongType(), True),                                     
    T.StructField("population", T.LongType(), True),                                    
    T.StructField("population_male", T.LongType(), True),                                   
    T.StructField("population_female", T.LongType(), True),                                     
    T.StructField("population_rural", T.LongType(), True),                                  
    T.StructField("population_urban", T.LongType(), True),                                  
    T.StructField("population_density", T.DoubleType(), True),                                  
    T.StructField("human_development_index", T.DoubleType(), True),                                     
    T.StructField("population_age_00_09", T.LongType(), True),                                  
    T.StructField("population_age_10_19", T.LongType(), True),                                  
    T.StructField("population_age_20_29", T.LongType(), True),                                  
    T.StructField("population_age_30_39", T.LongType(), True),                                  
    T.StructField("population_age_40_49", T.LongType(), True),                                  
    T.StructField("population_age_50_59", T.LongType(), True),                                  
    T.StructField("population_age_60_69", T.LongType(), True),                                  
    T.StructField("population_age_70_79", T.LongType(), True),                                  
    T.StructField("population_age_80_and_older", T.LongType(), True),                                   
    T.StructField("gdp_usd", T.LongType(), True),                                   
    T.StructField("gdp_per_capita_usd", T.LongType(), True),                                    
    T.StructField("openstreetmap_id", T.LongType(), True),                                  
    T.StructField("latitude", T.DoubleType(), True),                                    
    T.StructField("longitude", T.DoubleType(), True),                                   
    T.StructField("area_sq_km", T.LongType(), True),                                    
    T.StructField("smoking_prevalence", T.DoubleType(), True),                                  
    T.StructField("diabetes_prevalence", T.DoubleType(), True),                                     
    T.StructField("infant_mortality_rate", T.DoubleType(), True),                                   
    T.StructField("nurses_per_1000", T.DoubleType(), True),                                     
    T.StructField("physicians_per_1000", T.DoubleType(), True),                                     
    T.StructField("health_expenditure_usd", T.DoubleType(), True),                                  
    T.StructField("out_of_pocket_health_expenditure_usd", T.DoubleType(), True),                                    
    T.StructField("school_closing", T.LongType(), True),                                    
    T.StructField("workplace_closing", T.LongType(), True),                                     
    T.StructField("cancel_public_events", T.LongType(), True),                                  
    T.StructField("restrictions_on_gatherings", T.LongType(), True),                                    
    T.StructField("public_transport_closing", T.LongType(), True),                                  
    T.StructField("stay_at_home_requirements", T.LongType(), True),                                     
    T.StructField("restrictions_on_internal_movement", T.LongType(), True),                                     
    T.StructField("international_travel_controls", T.LongType(), True),                                     
    T.StructField("income_support", T.LongType(), True),                                    
    T.StructField("debt_relief", T.LongType(), True),                                   
    T.StructField("fiscal_measures", T.LongType(), True),                                   
    T.StructField("international_support", T.LongType(), True),                                     
    T.StructField("public_information_campaigns", T.LongType(), True),                                  
    T.StructField("testing_policy", T.LongType(), True),                                    
    T.StructField("contact_tracing", T.LongType(), True),                                   
    T.StructField("emergency_investment_in_healthcare", T.LongType(), True),                                    
    T.StructField("investment_in_vaccines", T.LongType(), True),                                    
    T.StructField("facial_coverings", T.LongType(), True),                                  
    T.StructField("vaccination_policy", T.LongType(), True),                                    
    T.StructField("stringency_index", T.DoubleType(), True),                                    
    T.StructField("average_temperature_celsius", T.DoubleType(), True),                                     
    T.StructField("minimum_temperature_celsius", T.DoubleType(), True),                                     
    T.StructField("maximum_temperature_celsius", T.DoubleType(), True),                                     
    T.StructField("rainfall_mm", T.DoubleType(), True),                                     
    T.StructField("snowfall_mm", T.DoubleType(), True),                                     
    T.StructField("dew_point", T.DoubleType(), True),                                   
    T.StructField("relative_humidity", T.DoubleType(), True),                                   
    T.StructField("new_tested", T.StringType(), True),                                  
    T.StructField("population_largest_city", T.StringType(), True),                                     
    T.StructField("population_clustered", T.StringType(), True),                                    
    T.StructField("human_capital_index", T.StringType(), True),                                     
    T.StructField("area_rural_sq_km", T.StringType(), True),                                    
    T.StructField("area_urban_sq_km", T.StringType(), True),                                    
    T.StructField("life_expectancy", T.StringType(), True),                                     
    T.StructField("adult_male_mortality_rate", T.StringType(), True),                                   
    T.StructField("adult_female_mortality_rate", T.StringType(), True),                                     
    T.StructField("pollution_mortality_rate", T.StringType(), True),                                    
    T.StructField("comorbidity_mortality_rate", T.StringType(), True),                                  
    T.StructField("mobility_retail_and_recreation", T.StringType(), True),                                  
    T.StructField("mobility_grocery_and_pharmacy", T.StringType(), True),                                   
    T.StructField("mobility_parks", T.StringType(), True),                                  
    T.StructField("mobility_transit_stations", T.StringType(), True),                                   
    T.StructField("mobility_workplaces", T.StringType(), True),                                     
    T.StructField("mobility_residential", T.StringType(), True),                                    
    T.StructField("hospital_beds_per_1000", T.DoubleType(), True),                                  
    T.StructField("subregion1_code", T.StringType(), True),                                     
    T.StructField("subregion1_name", T.StringType(), True),                                     
    T.StructField("new_recovered", T.LongType(), True),                                     
    T.StructField("cumulative_recovered", T.LongType(), True),                                  
    T.StructField("elevation_m", T.LongType(), True),                                   
    T.StructField("new_hospitalized_patients", T.LongType(), True),                                     
    T.StructField("cumulative_hospitalized_patients", T.LongType(), True),                                  
    T.StructField("new_intensive_care_patients", T.LongType(), True),                                   
    T.StructField("cumulative_intensive_care_patients", T.LongType(), True),                                    
    T.StructField("new_confirmed_age_0", T.LongType(), True),                                   
    T.StructField("new_confirmed_age_1", T.LongType(), True),                                   
    T.StructField("new_confirmed_age_2", T.LongType(), True),                                   
    T.StructField("new_confirmed_age_3", T.LongType(), True),                                   
    T.StructField("new_confirmed_age_4", T.LongType(), True),                                   
    T.StructField("new_confirmed_age_5", T.LongType(), True),                                   
    T.StructField("new_confirmed_age_6", T.LongType(), True),                                   
    T.StructField("new_confirmed_age_7", T.LongType(), True),                                   
    T.StructField("new_confirmed_age_8", T.LongType(), True),                                   
    T.StructField("new_confirmed_age_9", T.LongType(), True),                                   
    T.StructField("cumulative_confirmed_age_0", T.LongType(), True),                                    
    T.StructField("cumulative_confirmed_age_1", T.LongType(), True),                                    
    T.StructField("cumulative_confirmed_age_2", T.LongType(), True),                                    
    T.StructField("cumulative_confirmed_age_3", T.LongType(), True),                                    
    T.StructField("cumulative_confirmed_age_4", T.LongType(), True),                                    
    T.StructField("cumulative_confirmed_age_5", T.LongType(), True),                                    
    T.StructField("cumulative_confirmed_age_6", T.LongType(), True),                                    
    T.StructField("cumulative_confirmed_age_7", T.LongType(), True),                                    
    T.StructField("cumulative_confirmed_age_8", T.LongType(), True),                                    
    T.StructField("cumulative_confirmed_age_9", T.LongType(), True),                                    
    T.StructField("new_deceased_age_0", T.LongType(), True),                                    
    T.StructField("new_deceased_age_1", T.LongType(), True),                                    
    T.StructField("new_deceased_age_2", T.LongType(), True),                                    
    T.StructField("new_deceased_age_3", T.LongType(), True),                                    
    T.StructField("new_deceased_age_4", T.LongType(), True),                                    
    T.StructField("new_deceased_age_5", T.LongType(), True),                                    
    T.StructField("new_deceased_age_6", T.LongType(), True),                                    
    T.StructField("new_deceased_age_7", T.LongType(), True),                                    
    T.StructField("new_deceased_age_8", T.LongType(), True),                                    
    T.StructField("new_deceased_age_9", T.LongType(), True),                                    
    T.StructField("cumulative_deceased_age_0", T.LongType(), True),                                     
    T.StructField("cumulative_deceased_age_1", T.LongType(), True),                                     
    T.StructField("cumulative_deceased_age_2", T.LongType(), True),                                     
    T.StructField("cumulative_deceased_age_3", T.LongType(), True),                                     
    T.StructField("cumulative_deceased_age_4", T.LongType(), True),                                     
    T.StructField("cumulative_deceased_age_5", T.LongType(), True),                                     
    T.StructField("cumulative_deceased_age_6", T.LongType(), True),                                     
    T.StructField("cumulative_deceased_age_7", T.LongType(), True),                                     
    T.StructField("cumulative_deceased_age_8", T.LongType(), True),                                     
    T.StructField("cumulative_deceased_age_9", T.LongType(), True),                                     
    T.StructField("new_tested_age_0", T.LongType(), True),                                  
    T.StructField("new_tested_age_1", T.LongType(), True),                                  
    T.StructField("new_tested_age_2", T.LongType(), True),                                  
    T.StructField("new_tested_age_3", T.LongType(), True),                                  
    T.StructField("new_tested_age_4", T.LongType(), True),                                  
    T.StructField("new_tested_age_5", T.LongType(), True),                                  
    T.StructField("new_tested_age_6", T.LongType(), True),                                  
    T.StructField("new_tested_age_7", T.LongType(), True),                                  
    T.StructField("new_tested_age_8", T.LongType(), True),                                  
    T.StructField("new_tested_age_9", T.LongType(), True),                                  
    T.StructField("cumulative_tested_age_0", T.LongType(), True),                                   
    T.StructField("cumulative_tested_age_1", T.LongType(), True),                                   
    T.StructField("cumulative_tested_age_2", T.LongType(), True),                                   
    T.StructField("cumulative_tested_age_3", T.LongType(), True),                                   
    T.StructField("cumulative_tested_age_4", T.LongType(), True),                                   
    T.StructField("cumulative_tested_age_5", T.LongType(), True),                                   
    T.StructField("cumulative_tested_age_6", T.LongType(), True),                                   
    T.StructField("cumulative_tested_age_7", T.LongType(), True),                                   
    T.StructField("cumulative_tested_age_8", T.LongType(), True),                                   
    T.StructField("cumulative_tested_age_9", T.LongType(), True),                                   
    T.StructField("new_hospitalized_patients_age_0", T.LongType(), True),                                   
    T.StructField("new_hospitalized_patients_age_1", T.LongType(), True),                                   
    T.StructField("new_hospitalized_patients_age_2", T.LongType(), True),                                   
    T.StructField("new_hospitalized_patients_age_3", T.LongType(), True),                                   
    T.StructField("new_hospitalized_patients_age_4", T.LongType(), True),                                   
    T.StructField("new_hospitalized_patients_age_5", T.LongType(), True),                                   
    T.StructField("new_hospitalized_patients_age_6", T.LongType(), True),                                   
    T.StructField("new_hospitalized_patients_age_7", T.LongType(), True),                                   
    T.StructField("new_hospitalized_patients_age_8", T.LongType(), True),                                   
    T.StructField("new_hospitalized_patients_age_9", T.LongType(), True),                                   
    T.StructField("cumulative_hospitalized_patients_age_0", T.LongType(), True),                                    
    T.StructField("cumulative_hospitalized_patients_age_1", T.LongType(), True),                                    
    T.StructField("cumulative_hospitalized_patients_age_2", T.LongType(), True),                                    
    T.StructField("cumulative_hospitalized_patients_age_3", T.LongType(), True),                                    
    T.StructField("cumulative_hospitalized_patients_age_4", T.LongType(), True),                                    
    T.StructField("cumulative_hospitalized_patients_age_5", T.LongType(), True),                                    
    T.StructField("cumulative_hospitalized_patients_age_6", T.LongType(), True),                                    
    T.StructField("cumulative_hospitalized_patients_age_7", T.LongType(), True),                                    
    T.StructField("cumulative_hospitalized_patients_age_8", T.LongType(), True),                                    
    T.StructField("cumulative_hospitalized_patients_age_9", T.LongType(), True),                                    
    T.StructField("new_intensive_care_patients_age_0", T.LongType(), True),                                     
    T.StructField("new_intensive_care_patients_age_1", T.LongType(), True),                                     
    T.StructField("new_intensive_care_patients_age_2", T.LongType(), True),                                     
    T.StructField("new_intensive_care_patients_age_3", T.LongType(), True),                                     
    T.StructField("new_intensive_care_patients_age_4", T.LongType(), True),                                     
    T.StructField("new_intensive_care_patients_age_5", T.LongType(), True),                                     
    T.StructField("new_intensive_care_patients_age_6", T.LongType(), True),                                     
    T.StructField("new_intensive_care_patients_age_7", T.LongType(), True),                                     
    T.StructField("new_intensive_care_patients_age_8", T.LongType(), True),                                     
    T.StructField("new_intensive_care_patients_age_9", T.LongType(), True),                                     
    T.StructField("cumulative_intensive_care_patients_age_0", T.LongType(), True),                                  
    T.StructField("cumulative_intensive_care_patients_age_1", T.LongType(), True),                                  
    T.StructField("cumulative_intensive_care_patients_age_2", T.LongType(), True),                                  
    T.StructField("cumulative_intensive_care_patients_age_3", T.LongType(), True),                                  
    T.StructField("cumulative_intensive_care_patients_age_4", T.LongType(), True),                                  
    T.StructField("cumulative_intensive_care_patients_age_5", T.LongType(), True),                                  
    T.StructField("cumulative_intensive_care_patients_age_6", T.LongType(), True),                                  
    T.StructField("cumulative_intensive_care_patients_age_7", T.LongType(), True),                                  
    T.StructField("cumulative_intensive_care_patients_age_8", T.LongType(), True),                                  
    T.StructField("cumulative_intensive_care_patients_age_9", T.LongType(), True),                                  
    T.StructField("age_bin_0", T.StringType(), True),                                   
    T.StructField("age_bin_1", T.StringType(), True),                                   
    T.StructField("age_bin_2", T.StringType(), True),                                   
    T.StructField("age_bin_3", T.StringType(), True),                                   
    T.StructField("age_bin_4", T.StringType(), True),                                   
    T.StructField("age_bin_5", T.StringType(), True),                                   
    T.StructField("age_bin_6", T.StringType(), True),                                   
    T.StructField("age_bin_7", T.StringType(), True),                                   
    T.StructField("age_bin_8", T.StringType(), True),                                   
    T.StructField("age_bin_9", T.StringType(), True),                                   
    T.StructField("new_confirmed_male", T.LongType(), True),                                    
    T.StructField("new_confirmed_female", T.LongType(), True),                                  
    T.StructField("cumulative_confirmed_male", T.LongType(), True),                                     
    T.StructField("cumulative_confirmed_female", T.LongType(), True),                                   
    T.StructField("new_deceased_male", T.LongType(), True),                                     
    T.StructField("new_deceased_female", T.LongType(), True),                                   
    T.StructField("cumulative_deceased_male", T.LongType(), True),                                  
    T.StructField("cumulative_deceased_female", T.LongType(), True),                                    
    T.StructField("new_tested_male", T.LongType(), True),                                   
    T.StructField("new_tested_female", T.LongType(), True),                                     
    T.StructField("cumulative_tested_male", T.LongType(), True),                                    
    T.StructField("cumulative_tested_female", T.LongType(), True),                                  
    T.StructField("new_hospitalized_patients_male", T.LongType(), True),                                    
    T.StructField("new_hospitalized_patients_female", T.LongType(), True),                                  
    T.StructField("cumulative_hospitalized_patients_male", T.LongType(), True),                                     
    T.StructField("cumulative_hospitalized_patients_female", T.LongType(), True),                                   
    T.StructField("new_intensive_care_patients_male", T.LongType(), True),                                  
    T.StructField("new_intensive_care_patients_female", T.LongType(), True),                                    
    T.StructField("cumulative_intensive_care_patients_male", T.LongType(), True),                                   
    T.StructField("cumulative_intensive_care_patients_female", T.LongType(), True),                                     
    T.StructField("subregion2_code", T.StringType(), True),                                     
    T.StructField("subregion2_name", T.StringType(), True),                                     
    T.StructField("current_hospitalized_patients", T.LongType(), True),                                     
    T.StructField("current_intensive_care_patients", T.LongType(), True),                                   
    T.StructField("current_ventilator_patients", T.LongType(), True),                                   
    T.StructField("search_trends_abdominal_obesity", T.DoubleType(), True),                                     
    T.StructField("search_trends_abdominal_pain", T.DoubleType(), True),                                    
    T.StructField("search_trends_acne", T.DoubleType(), True),                                  
    T.StructField("search_trends_actinic_keratosis", T.DoubleType(), True),                                     
    T.StructField("search_trends_acute_bronchitis", T.DoubleType(), True),                                  
    T.StructField("search_trends_adrenal_crisis", T.DoubleType(), True),                                    
    T.StructField("search_trends_ageusia", T.DoubleType(), True),                                   
    T.StructField("search_trends_alcoholism", T.DoubleType(), True),                                    
    T.StructField("search_trends_allergic_conjunctivitis", T.DoubleType(), True),                                   
    T.StructField("search_trends_allergy", T.DoubleType(), True),                                   
    T.StructField("search_trends_amblyopia", T.DoubleType(), True),                                     
    T.StructField("search_trends_amenorrhea", T.DoubleType(), True),                                    
    T.StructField("search_trends_amnesia", T.DoubleType(), True),                                   
    T.StructField("search_trends_anal_fissure", T.DoubleType(), True),                                  
    T.StructField("search_trends_anaphylaxis", T.DoubleType(), True),                                   
    T.StructField("search_trends_anemia", T.DoubleType(), True),                                    
    T.StructField("search_trends_angina_pectoris", T.DoubleType(), True),                                   
    T.StructField("search_trends_angioedema", T.DoubleType(), True),                                    
    T.StructField("search_trends_angular_cheilitis", T.DoubleType(), True),                                     
    T.StructField("search_trends_anosmia", T.DoubleType(), True),                                   
    T.StructField("search_trends_anxiety", T.DoubleType(), True),                                   
    T.StructField("search_trends_aphasia", T.DoubleType(), True),                                   
    T.StructField("search_trends_aphonia", T.DoubleType(), True),                                   
    T.StructField("search_trends_apnea", T.DoubleType(), True),                                     
    T.StructField("search_trends_arthralgia", T.DoubleType(), True),                                    
    T.StructField("search_trends_arthritis", T.DoubleType(), True),                                     
    T.StructField("search_trends_ascites", T.DoubleType(), True),                                   
    T.StructField("search_trends_asperger_syndrome", T.DoubleType(), True),                                     
    T.StructField("search_trends_asphyxia", T.DoubleType(), True),                                  
    T.StructField("search_trends_asthma", T.DoubleType(), True),                                    
    T.StructField("search_trends_astigmatism", T.DoubleType(), True),                                   
    T.StructField("search_trends_ataxia", T.DoubleType(), True),                                    
    T.StructField("search_trends_atheroma", T.DoubleType(), True),                                  
    T.StructField("search_trends_attention_deficit_hyperactivity_disorder", T.DoubleType(), True),                                  
    T.StructField("search_trends_auditory_hallucination", T.DoubleType(), True),                                    
    T.StructField("search_trends_autoimmune_disease", T.DoubleType(), True),                                    
    T.StructField("search_trends_avoidant_personality_disorder", T.DoubleType(), True),                                     
    T.StructField("search_trends_back_pain", T.DoubleType(), True),                                     
    T.StructField("search_trends_bacterial_vaginosis", T.DoubleType(), True),                                   
    T.StructField("search_trends_balance_disorder", T.DoubleType(), True),                                  
    T.StructField("search_trends_beaus_lines", T.DoubleType(), True),                                   
    T.StructField("search_trends_bells_palsy", T.DoubleType(), True),                                   
    T.StructField("search_trends_biliary_colic", T.DoubleType(), True),                                     
    T.StructField("search_trends_binge_eating", T.DoubleType(), True),                                  
    T.StructField("search_trends_bleeding", T.DoubleType(), True),                                  
    T.StructField("search_trends_bleeding_on_probing", T.DoubleType(), True),                                   
    T.StructField("search_trends_blepharospasm", T.DoubleType(), True),                                     
    T.StructField("search_trends_bloating", T.DoubleType(), True),                                  
    T.StructField("search_trends_blood_in_stool", T.DoubleType(), True),                                    
    T.StructField("search_trends_blurred_vision", T.DoubleType(), True),                                    
    T.StructField("search_trends_blushing", T.DoubleType(), True),                                  
    T.StructField("search_trends_boil", T.DoubleType(), True),                                  
    T.StructField("search_trends_bone_fracture", T.DoubleType(), True),                                     
    T.StructField("search_trends_bone_tumor", T.DoubleType(), True),                                    
    T.StructField("search_trends_bowel_obstruction", T.DoubleType(), True),                                     
    T.StructField("search_trends_bradycardia", T.DoubleType(), True),                                   
    T.StructField("search_trends_braxton_hicks_contractions", T.DoubleType(), True),                                    
    T.StructField("search_trends_breakthrough_bleeding", T.DoubleType(), True),                                     
    T.StructField("search_trends_breast_pain", T.DoubleType(), True),                                   
    T.StructField("search_trends_bronchitis", T.DoubleType(), True),                                    
    T.StructField("search_trends_bruise", T.DoubleType(), True),                                    
    T.StructField("search_trends_bruxism", T.DoubleType(), True),                                   
    T.StructField("search_trends_bunion", T.DoubleType(), True),                                    
    T.StructField("search_trends_burn", T.DoubleType(), True),                                  
    T.StructField("search_trends_burning_chest_pain", T.DoubleType(), True),                                    
    T.StructField("search_trends_burning_mouth_syndrome", T.DoubleType(), True),                                    
    T.StructField("search_trends_candidiasis", T.DoubleType(), True),                                   
    T.StructField("search_trends_canker_sore", T.DoubleType(), True),                                   
    T.StructField("search_trends_cardiac_arrest", T.DoubleType(), True),                                    
    T.StructField("search_trends_carpal_tunnel_syndrome", T.DoubleType(), True),                                    
    T.StructField("search_trends_cataplexy", T.DoubleType(), True),                                     
    T.StructField("search_trends_cataract", T.DoubleType(), True),                                  
    T.StructField("search_trends_chancre", T.DoubleType(), True),                                   
    T.StructField("search_trends_cheilitis", T.DoubleType(), True),                                     
    T.StructField("search_trends_chest_pain", T.DoubleType(), True),                                    
    T.StructField("search_trends_chills", T.DoubleType(), True),                                    
    T.StructField("search_trends_chorea", T.DoubleType(), True),                                    
    T.StructField("search_trends_chronic_pain", T.DoubleType(), True),                                  
    T.StructField("search_trends_cirrhosis", T.DoubleType(), True),                                     
    T.StructField("search_trends_cleft_lip_and_cleft_palate", T.DoubleType(), True),                                    
    T.StructField("search_trends_clouding_of_consciousness", T.DoubleType(), True),                                     
    T.StructField("search_trends_cluster_headache", T.DoubleType(), True),                                  
    T.StructField("search_trends_colitis", T.DoubleType(), True),                                   
    T.StructField("search_trends_coma", T.DoubleType(), True),                                  
    T.StructField("search_trends_common_cold", T.DoubleType(), True),                                   
    T.StructField("search_trends_compulsive_behavior", T.DoubleType(), True),                                   
    T.StructField("search_trends_compulsive_hoarding", T.DoubleType(), True),                                   
    T.StructField("search_trends_confusion", T.DoubleType(), True),                                     
    T.StructField("search_trends_congenital_heart_defect", T.DoubleType(), True),                                   
    T.StructField("search_trends_conjunctivitis", T.DoubleType(), True),                                    
    T.StructField("search_trends_constipation", T.DoubleType(), True),                                  
    T.StructField("search_trends_convulsion", T.DoubleType(), True),                                    
    T.StructField("search_trends_cough", T.DoubleType(), True),                                     
    T.StructField("search_trends_crackles", T.DoubleType(), True),                                  
    T.StructField("search_trends_cramp", T.DoubleType(), True),                                     
    T.StructField("search_trends_crepitus", T.DoubleType(), True),                                  
    T.StructField("search_trends_croup", T.DoubleType(), True),                                     
    T.StructField("search_trends_cyanosis", T.DoubleType(), True),                                  
    T.StructField("search_trends_dandruff", T.DoubleType(), True),                                  
    T.StructField("search_trends_delayed_onset_muscle_soreness", T.DoubleType(), True),                                     
    T.StructField("search_trends_dementia", T.DoubleType(), True),                                  
    T.StructField("search_trends_dentin_hypersensitivity", T.DoubleType(), True),                                   
    T.StructField("search_trends_depersonalization", T.DoubleType(), True),                                     
    T.StructField("search_trends_depression", T.DoubleType(), True),                                    
    T.StructField("search_trends_dermatitis", T.DoubleType(), True),                                    
    T.StructField("search_trends_desquamation", T.DoubleType(), True),                                  
    T.StructField("search_trends_developmental_disability", T.DoubleType(), True),                                  
    T.StructField("search_trends_diabetes", T.DoubleType(), True),                                  
    T.StructField("search_trends_diabetic_ketoacidosis", T.DoubleType(), True),                                     
    T.StructField("search_trends_diarrhea", T.DoubleType(), True),                                  
    T.StructField("search_trends_dizziness", T.DoubleType(), True),                                     
    T.StructField("search_trends_dry_eye_syndrome", T.DoubleType(), True),                                  
    T.StructField("search_trends_dysautonomia", T.DoubleType(), True),                                  
    T.StructField("search_trends_dysgeusia", T.DoubleType(), True),                                     
    T.StructField("search_trends_dysmenorrhea", T.DoubleType(), True),                                  
    T.StructField("search_trends_dyspareunia", T.DoubleType(), True),                                   
    T.StructField("search_trends_dysphagia", T.DoubleType(), True),                                     
    T.StructField("search_trends_dysphoria", T.DoubleType(), True),                                     
    T.StructField("search_trends_dystonia", T.DoubleType(), True),                                  
    T.StructField("search_trends_dysuria", T.DoubleType(), True),                                   
    T.StructField("search_trends_ear_pain", T.DoubleType(), True),                                  
    T.StructField("search_trends_eczema", T.DoubleType(), True),                                    
    T.StructField("search_trends_edema", T.DoubleType(), True),                                     
    T.StructField("search_trends_encephalitis", T.DoubleType(), True),                                  
    T.StructField("search_trends_encephalopathy", T.DoubleType(), True),                                    
    T.StructField("search_trends_epidermoid_cyst", T.DoubleType(), True),                                   
    T.StructField("search_trends_epilepsy", T.DoubleType(), True),                                  
    T.StructField("search_trends_epiphora", T.DoubleType(), True),                                  
    T.StructField("search_trends_erectile_dysfunction", T.DoubleType(), True),                                  
    T.StructField("search_trends_erythema", T.DoubleType(), True),                                  
    T.StructField("search_trends_erythema_chronicum_migrans", T.DoubleType(), True),                                    
    T.StructField("search_trends_esophagitis", T.DoubleType(), True),                                   
    T.StructField("search_trends_excessive_daytime_sleepiness", T.DoubleType(), True),                                  
    T.StructField("search_trends_eye_pain", T.DoubleType(), True),                                  
    T.StructField("search_trends_eye_strain", T.DoubleType(), True),                                    
    T.StructField("search_trends_facial_nerve_paralysis", T.DoubleType(), True),                                    
    T.StructField("search_trends_facial_swelling", T.DoubleType(), True),                                   
    T.StructField("search_trends_fasciculation", T.DoubleType(), True),                                     
    T.StructField("search_trends_fatigue", T.DoubleType(), True),                                   
    T.StructField("search_trends_fatty_liver_disease", T.DoubleType(), True),                                   
    T.StructField("search_trends_fecal_incontinence", T.DoubleType(), True),                                    
    T.StructField("search_trends_fever", T.DoubleType(), True),                                     
    T.StructField("search_trends_fibrillation", T.DoubleType(), True),                                  
    T.StructField("search_trends_fibrocystic_breast_changes", T.DoubleType(), True),                                    
    T.StructField("search_trends_fibromyalgia", T.DoubleType(), True),                                  
    T.StructField("search_trends_flatulence", T.DoubleType(), True),                                    
    T.StructField("search_trends_floater", T.DoubleType(), True),                                   
    T.StructField("search_trends_focal_seizure", T.DoubleType(), True),                                     
    T.StructField("search_trends_folate_deficiency", T.DoubleType(), True),                                     
    T.StructField("search_trends_food_craving", T.DoubleType(), True),                                  
    T.StructField("search_trends_food_intolerance", T.DoubleType(), True),                                  
    T.StructField("search_trends_frequent_urination", T.DoubleType(), True),                                    
    T.StructField("search_trends_gastroesophageal_reflux_disease", T.DoubleType(), True),                                   
    T.StructField("search_trends_gastroparesis", T.DoubleType(), True),                                     
    T.StructField("search_trends_generalized_anxiety_disorder", T.DoubleType(), True),                                  
    T.StructField("search_trends_genital_wart", T.DoubleType(), True),                                  
    T.StructField("search_trends_gingival_recession", T.DoubleType(), True),                                    
    T.StructField("search_trends_gingivitis", T.DoubleType(), True),                                    
    T.StructField("search_trends_globus_pharyngis", T.DoubleType(), True),                                  
    T.StructField("search_trends_goitre", T.DoubleType(), True),                                    
    T.StructField("search_trends_gout", T.DoubleType(), True),                                  
    T.StructField("search_trends_grandiosity", T.DoubleType(), True),                                   
    T.StructField("search_trends_granuloma", T.DoubleType(), True),                                     
    T.StructField("search_trends_guilt", T.DoubleType(), True),                                     
    T.StructField("search_trends_hair_loss", T.DoubleType(), True),                                     
    T.StructField("search_trends_halitosis", T.DoubleType(), True),                                     
    T.StructField("search_trends_hay_fever", T.DoubleType(), True),                                     
    T.StructField("search_trends_headache", T.DoubleType(), True),                                  
    T.StructField("search_trends_heart_arrhythmia", T.DoubleType(), True),                                  
    T.StructField("search_trends_heart_murmur", T.DoubleType(), True),                                  
    T.StructField("search_trends_heartburn", T.DoubleType(), True),                                     
    T.StructField("search_trends_hematochezia", T.DoubleType(), True),                                  
    T.StructField("search_trends_hematoma", T.DoubleType(), True),                                  
    T.StructField("search_trends_hematuria", T.DoubleType(), True),                                     
    T.StructField("search_trends_hemolysis", T.DoubleType(), True),                                     
    T.StructField("search_trends_hemoptysis", T.DoubleType(), True),                                    
    T.StructField("search_trends_hemorrhoids", T.DoubleType(), True),                                   
    T.StructField("search_trends_hepatic_encephalopathy", T.DoubleType(), True),                                    
    T.StructField("search_trends_hepatitis", T.DoubleType(), True),                                     
    T.StructField("search_trends_hepatotoxicity", T.DoubleType(), True),                                    
    T.StructField("search_trends_hiccup", T.DoubleType(), True),                                    
    T.StructField("search_trends_hip_pain", T.DoubleType(), True),                                  
    T.StructField("search_trends_hives", T.DoubleType(), True),                                     
    T.StructField("search_trends_hot_flash", T.DoubleType(), True),                                     
    T.StructField("search_trends_hydrocephalus", T.DoubleType(), True),                                     
    T.StructField("search_trends_hypercalcaemia", T.DoubleType(), True),                                    
    T.StructField("search_trends_hypercapnia", T.DoubleType(), True),                                   
    T.StructField("search_trends_hypercholesterolemia", T.DoubleType(), True),                                  
    T.StructField("search_trends_hyperemesis_gravidarum", T.DoubleType(), True),                                    
    T.StructField("search_trends_hyperglycemia", T.DoubleType(), True),                                     
    T.StructField("search_trends_hyperhidrosis", T.DoubleType(), True),                                     
    T.StructField("search_trends_hyperkalemia", T.DoubleType(), True),                                  
    T.StructField("search_trends_hyperlipidemia", T.DoubleType(), True),                                    
    T.StructField("search_trends_hypermobility", T.DoubleType(), True),                                     
    T.StructField("search_trends_hyperpigmentation", T.DoubleType(), True),                                     
    T.StructField("search_trends_hypersomnia", T.DoubleType(), True),                                   
    T.StructField("search_trends_hypertension", T.DoubleType(), True),                                  
    T.StructField("search_trends_hyperthermia", T.DoubleType(), True),                                  
    T.StructField("search_trends_hyperthyroidism", T.DoubleType(), True),                                   
    T.StructField("search_trends_hypertriglyceridemia", T.DoubleType(), True),                                  
    T.StructField("search_trends_hypertrophy", T.DoubleType(), True),                                   
    T.StructField("search_trends_hyperventilation", T.DoubleType(), True),                                  
    T.StructField("search_trends_hypocalcaemia", T.DoubleType(), True),                                     
    T.StructField("search_trends_hypochondriasis", T.DoubleType(), True),                                   
    T.StructField("search_trends_hypoglycemia", T.DoubleType(), True),                                  
    T.StructField("search_trends_hypogonadism", T.DoubleType(), True),                                  
    T.StructField("search_trends_hypokalemia", T.DoubleType(), True),                                   
    T.StructField("search_trends_hypomania", T.DoubleType(), True),                                     
    T.StructField("search_trends_hyponatremia", T.DoubleType(), True),                                  
    T.StructField("search_trends_hypotension", T.DoubleType(), True),                                   
    T.StructField("search_trends_hypothyroidism", T.DoubleType(), True),                                    
    T.StructField("search_trends_hypoxemia", T.DoubleType(), True),                                     
    T.StructField("search_trends_hypoxia", T.DoubleType(), True),                                   
    T.StructField("search_trends_impetigo", T.DoubleType(), True),                                  
    T.StructField("search_trends_implantation_bleeding", T.DoubleType(), True),                                     
    T.StructField("search_trends_impulsivity", T.DoubleType(), True),                                   
    T.StructField("search_trends_indigestion", T.DoubleType(), True),                                   
    T.StructField("search_trends_infection", T.DoubleType(), True),                                     
    T.StructField("search_trends_inflammation", T.DoubleType(), True),                                  
    T.StructField("search_trends_inflammatory_bowel_disease", T.DoubleType(), True),                                    
    T.StructField("search_trends_ingrown_hair", T.DoubleType(), True),                                  
    T.StructField("search_trends_insomnia", T.DoubleType(), True),                                  
    T.StructField("search_trends_insulin_resistance", T.DoubleType(), True),                                    
    T.StructField("search_trends_intermenstrual_bleeding", T.DoubleType(), True),                                   
    T.StructField("search_trends_intracranial_pressure", T.DoubleType(), True),                                     
    T.StructField("search_trends_iron_deficiency", T.DoubleType(), True),                                   
    T.StructField("search_trends_irregular_menstruation", T.DoubleType(), True),                                    
    T.StructField("search_trends_itch", T.DoubleType(), True),                                  
    T.StructField("search_trends_jaundice", T.DoubleType(), True),                                  
    T.StructField("search_trends_kidney_failure", T.DoubleType(), True),                                    
    T.StructField("search_trends_kidney_stone", T.DoubleType(), True),                                  
    T.StructField("search_trends_knee_pain", T.DoubleType(), True),                                     
    T.StructField("search_trends_kyphosis", T.DoubleType(), True),                                  
    T.StructField("search_trends_lactose_intolerance", T.DoubleType(), True),                                   
    T.StructField("search_trends_laryngitis", T.DoubleType(), True),                                    
    T.StructField("search_trends_leg_cramps", T.DoubleType(), True),                                    
    T.StructField("search_trends_lesion", T.DoubleType(), True),                                    
    T.StructField("search_trends_leukorrhea", T.DoubleType(), True),                                    
    T.StructField("search_trends_lightheadedness", T.DoubleType(), True),                                   
    T.StructField("search_trends_low_back_pain", T.DoubleType(), True),                                     
    T.StructField("search_trends_low_grade_fever", T.DoubleType(), True),                                   
    T.StructField("search_trends_lymphedema", T.DoubleType(), True),                                    
    T.StructField("search_trends_major_depressive_disorder", T.DoubleType(), True),                                     
    T.StructField("search_trends_malabsorption", T.DoubleType(), True),                                     
    T.StructField("search_trends_male_infertility", T.DoubleType(), True),                                  
    T.StructField("search_trends_manic_disorder", T.DoubleType(), True),                                    
    T.StructField("search_trends_melasma", T.DoubleType(), True),                                   
    T.StructField("search_trends_melena", T.DoubleType(), True),                                    
    T.StructField("search_trends_meningitis", T.DoubleType(), True),                                    
    T.StructField("search_trends_menorrhagia", T.DoubleType(), True),                                   
    T.StructField("search_trends_middle_back_pain", T.DoubleType(), True),                                  
    T.StructField("search_trends_migraine", T.DoubleType(), True),                                  
    T.StructField("search_trends_milium", T.DoubleType(), True),                                    
    T.StructField("search_trends_mitral_insufficiency", T.DoubleType(), True),                                  
    T.StructField("search_trends_mood_disorder", T.DoubleType(), True),                                     
    T.StructField("search_trends_mood_swing", T.DoubleType(), True),                                    
    T.StructField("search_trends_morning_sickness", T.DoubleType(), True),                                  
    T.StructField("search_trends_motion_sickness", T.DoubleType(), True),                                   
    T.StructField("search_trends_mouth_ulcer", T.DoubleType(), True),                                   
    T.StructField("search_trends_muscle_atrophy", T.DoubleType(), True),                                    
    T.StructField("search_trends_muscle_weakness", T.DoubleType(), True),                                   
    T.StructField("search_trends_myalgia", T.DoubleType(), True),                                   
    T.StructField("search_trends_mydriasis", T.DoubleType(), True),                                     
    T.StructField("search_trends_myocardial_infarction", T.DoubleType(), True),                                     
    T.StructField("search_trends_myoclonus", T.DoubleType(), True),                                     
    T.StructField("search_trends_nasal_congestion", T.DoubleType(), True),                                  
    T.StructField("search_trends_nasal_polyp", T.DoubleType(), True),                                   
    T.StructField("search_trends_nausea", T.DoubleType(), True),                                    
    T.StructField("search_trends_neck_mass", T.DoubleType(), True),                                     
    T.StructField("search_trends_neck_pain", T.DoubleType(), True),                                     
    T.StructField("search_trends_neonatal_jaundice", T.DoubleType(), True),                                     
    T.StructField("search_trends_nerve_injury", T.DoubleType(), True),                                  
    T.StructField("search_trends_neuralgia", T.DoubleType(), True),                                     
    T.StructField("search_trends_neutropenia", T.DoubleType(), True),                                   
    T.StructField("search_trends_night_sweats", T.DoubleType(), True),                                  
    T.StructField("search_trends_night_terror", T.DoubleType(), True),                                  
    T.StructField("search_trends_nocturnal_enuresis", T.DoubleType(), True),                                    
    T.StructField("search_trends_nodule", T.DoubleType(), True),                                    
    T.StructField("search_trends_nosebleed", T.DoubleType(), True),                                     
    T.StructField("search_trends_nystagmus", T.DoubleType(), True),                                     
    T.StructField("search_trends_obesity", T.DoubleType(), True),                                   
    T.StructField("search_trends_onychorrhexis", T.DoubleType(), True),                                     
    T.StructField("search_trends_oral_candidiasis", T.DoubleType(), True),                                  
    T.StructField("search_trends_orthostatic_hypotension", T.DoubleType(), True),                                   
    T.StructField("search_trends_osteopenia", T.DoubleType(), True),                                    
    T.StructField("search_trends_osteophyte", T.DoubleType(), True),                                    
    T.StructField("search_trends_osteoporosis", T.DoubleType(), True),                                  
    T.StructField("search_trends_otitis", T.DoubleType(), True),                                    
    T.StructField("search_trends_otitis_externa", T.DoubleType(), True),                                    
    T.StructField("search_trends_otitis_media", T.DoubleType(), True),                                  
    T.StructField("search_trends_pain", T.DoubleType(), True),                                  
    T.StructField("search_trends_palpitations", T.DoubleType(), True),                                  
    T.StructField("search_trends_pancreatitis", T.DoubleType(), True),                                  
    T.StructField("search_trends_panic_attack", T.DoubleType(), True),                                  
    T.StructField("search_trends_papule", T.DoubleType(), True),                                    
    T.StructField("search_trends_paranoia", T.DoubleType(), True),                                  
    T.StructField("search_trends_paresthesia", T.DoubleType(), True),                                   
    T.StructField("search_trends_pelvic_inflammatory_disease", T.DoubleType(), True),                                   
    T.StructField("search_trends_pericarditis", T.DoubleType(), True),                                  
    T.StructField("search_trends_periodontal_disease", T.DoubleType(), True),                                   
    T.StructField("search_trends_periorbital_puffiness", T.DoubleType(), True),                                     
    T.StructField("search_trends_peripheral_neuropathy", T.DoubleType(), True),                                     
    T.StructField("search_trends_perspiration", T.DoubleType(), True),                                  
    T.StructField("search_trends_petechia", T.DoubleType(), True),                                  
    T.StructField("search_trends_phlegm", T.DoubleType(), True),                                    
    T.StructField("search_trends_photodermatitis", T.DoubleType(), True),                                   
    T.StructField("search_trends_photophobia", T.DoubleType(), True),                                   
    T.StructField("search_trends_photopsia", T.DoubleType(), True),                                     
    T.StructField("search_trends_pleural_effusion", T.DoubleType(), True),                                  
    T.StructField("search_trends_pleurisy", T.DoubleType(), True),                                  
    T.StructField("search_trends_pneumonia", T.DoubleType(), True),                                     
    T.StructField("search_trends_podalgia", T.DoubleType(), True),                                  
    T.StructField("search_trends_polycythemia", T.DoubleType(), True),                                  
    T.StructField("search_trends_polydipsia", T.DoubleType(), True),                                    
    T.StructField("search_trends_polyneuropathy", T.DoubleType(), True),                                    
    T.StructField("search_trends_polyuria", T.DoubleType(), True),                                  
    T.StructField("search_trends_poor_posture", T.DoubleType(), True),                                  
    T.StructField("search_trends_post_nasal_drip", T.DoubleType(), True),                                   
    T.StructField("search_trends_postural_orthostatic_tachycardia_syndrome", T.DoubleType(), True),                                     
    T.StructField("search_trends_prediabetes", T.DoubleType(), True),                                   
    T.StructField("search_trends_proteinuria", T.DoubleType(), True),                                   
    T.StructField("search_trends_pruritus_ani", T.DoubleType(), True),                                  
    T.StructField("search_trends_psychosis", T.DoubleType(), True),                                     
    T.StructField("search_trends_ptosis", T.DoubleType(), True),                                    
    T.StructField("search_trends_pulmonary_edema", T.DoubleType(), True),                                   
    T.StructField("search_trends_pulmonary_hypertension", T.DoubleType(), True),                                    
    T.StructField("search_trends_purpura", T.DoubleType(), True),                                   
    T.StructField("search_trends_pus", T.DoubleType(), True),                                   
    T.StructField("search_trends_pyelonephritis", T.DoubleType(), True),                                    
    T.StructField("search_trends_radiculopathy", T.DoubleType(), True),                                     
    T.StructField("search_trends_rectal_pain", T.DoubleType(), True),                                   
    T.StructField("search_trends_rectal_prolapse", T.DoubleType(), True),                                   
    T.StructField("search_trends_red_eye", T.DoubleType(), True),                                   
    T.StructField("search_trends_renal_colic", T.DoubleType(), True),                                   
    T.StructField("search_trends_restless_legs_syndrome", T.DoubleType(), True),                                    
    T.StructField("search_trends_rheum", T.DoubleType(), True),                                     
    T.StructField("search_trends_rhinitis", T.DoubleType(), True),                                  
    T.StructField("search_trends_rhinorrhea", T.DoubleType(), True),                                    
    T.StructField("search_trends_rosacea", T.DoubleType(), True),                                   
    T.StructField("search_trends_round_ligament_pain", T.DoubleType(), True),                                   
    T.StructField("search_trends_rumination", T.DoubleType(), True),                                    
    T.StructField("search_trends_scar", T.DoubleType(), True),                                  
    T.StructField("search_trends_sciatica", T.DoubleType(), True),                                  
    T.StructField("search_trends_scoliosis", T.DoubleType(), True),                                     
    T.StructField("search_trends_seborrheic_dermatitis", T.DoubleType(), True),                                     
    T.StructField("search_trends_self_harm", T.DoubleType(), True),                                     
    T.StructField("search_trends_sensitivity_to_sound", T.DoubleType(), True),                                  
    T.StructField("search_trends_sexual_dysfunction", T.DoubleType(), True),                                    
    T.StructField("search_trends_shallow_breathing", T.DoubleType(), True),                                     
    T.StructField("search_trends_sharp_pain", T.DoubleType(), True),                                    
    T.StructField("search_trends_shivering", T.DoubleType(), True),                                     
    T.StructField("search_trends_shortness_of_breath", T.DoubleType(), True),                                   
    T.StructField("search_trends_shyness", T.DoubleType(), True),                                   
    T.StructField("search_trends_sinusitis", T.DoubleType(), True),                                     
    T.StructField("search_trends_skin_condition", T.DoubleType(), True),                                    
    T.StructField("search_trends_skin_rash", T.DoubleType(), True),                                     
    T.StructField("search_trends_skin_tag", T.DoubleType(), True),                                  
    T.StructField("search_trends_skin_ulcer", T.DoubleType(), True),                                    
    T.StructField("search_trends_sleep_apnea", T.DoubleType(), True),                                   
    T.StructField("search_trends_sleep_deprivation", T.DoubleType(), True),                                     
    T.StructField("search_trends_sleep_disorder", T.DoubleType(), True),                                    
    T.StructField("search_trends_snoring", T.DoubleType(), True),                                   
    T.StructField("search_trends_sore_throat", T.DoubleType(), True),                                   
    T.StructField("search_trends_spasticity", T.DoubleType(), True),                                    
    T.StructField("search_trends_splenomegaly", T.DoubleType(), True),                                  
    T.StructField("search_trends_sputum", T.DoubleType(), True),                                    
    T.StructField("search_trends_stomach_rumble", T.DoubleType(), True),                                    
    T.StructField("search_trends_strabismus", T.DoubleType(), True),                                    
    T.StructField("search_trends_stretch_marks", T.DoubleType(), True),                                     
    T.StructField("search_trends_stridor", T.DoubleType(), True),                                   
    T.StructField("search_trends_stroke", T.DoubleType(), True),                                    
    T.StructField("search_trends_stuttering", T.DoubleType(), True),                                    
    T.StructField("search_trends_subdural_hematoma", T.DoubleType(), True),                                     
    T.StructField("search_trends_suicidal_ideation", T.DoubleType(), True),                                     
    T.StructField("search_trends_swelling", T.DoubleType(), True),                                  
    T.StructField("search_trends_swollen_feet", T.DoubleType(), True),                                  
    T.StructField("search_trends_swollen_lymph_nodes", T.DoubleType(), True),                                   
    T.StructField("search_trends_syncope", T.DoubleType(), True),                                   
    T.StructField("search_trends_tachycardia", T.DoubleType(), True),                                   
    T.StructField("search_trends_tachypnea", T.DoubleType(), True),                                     
    T.StructField("search_trends_telangiectasia", T.DoubleType(), True),                                    
    T.StructField("search_trends_tenderness", T.DoubleType(), True),                                    
    T.StructField("search_trends_testicular_pain", T.DoubleType(), True),                                   
    T.StructField("search_trends_throat_irritation", T.DoubleType(), True),                                     
    T.StructField("search_trends_thrombocytopenia", T.DoubleType(), True),                                  
    T.StructField("search_trends_thyroid_nodule", T.DoubleType(), True),                                    
    T.StructField("search_trends_tic", T.DoubleType(), True),                                   
    T.StructField("search_trends_tinnitus", T.DoubleType(), True),                                  
    T.StructField("search_trends_tonsillitis", T.DoubleType(), True),                                   
    T.StructField("search_trends_toothache", T.DoubleType(), True),                                     
    T.StructField("search_trends_tremor", T.DoubleType(), True),                                    
    T.StructField("search_trends_trichoptilosis", T.DoubleType(), True),                                    
    T.StructField("search_trends_tumor", T.DoubleType(), True),                                     
    T.StructField("search_trends_type_2_diabetes", T.DoubleType(), True),                                   
    T.StructField("search_trends_unconsciousness", T.DoubleType(), True),                                   
    T.StructField("search_trends_underweight", T.DoubleType(), True),                                   
    T.StructField("search_trends_upper_respiratory_tract_infection", T.DoubleType(), True),                                     
    T.StructField("search_trends_urethritis", T.DoubleType(), True),                                    
    T.StructField("search_trends_urinary_incontinence", T.DoubleType(), True),                                  
    T.StructField("search_trends_urinary_tract_infection", T.DoubleType(), True),                                   
    T.StructField("search_trends_urinary_urgency", T.DoubleType(), True),                                   
    T.StructField("search_trends_uterine_contraction", T.DoubleType(), True),                                   
    T.StructField("search_trends_vaginal_bleeding", T.DoubleType(), True),                                  
    T.StructField("search_trends_vaginal_discharge", T.DoubleType(), True),                                     
    T.StructField("search_trends_vaginitis", T.DoubleType(), True),                                     
    T.StructField("search_trends_varicose_veins", T.DoubleType(), True),                                    
    T.StructField("search_trends_vasculitis", T.DoubleType(), True),                                    
    T.StructField("search_trends_ventricular_fibrillation", T.DoubleType(), True),                                  
    T.StructField("search_trends_ventricular_tachycardia", T.DoubleType(), True),                                   
    T.StructField("search_trends_vertigo", T.DoubleType(), True),                                   
    T.StructField("search_trends_viral_pneumonia", T.DoubleType(), True),                                   
    T.StructField("search_trends_visual_acuity", T.DoubleType(), True),                                     
    T.StructField("search_trends_vomiting", T.DoubleType(), True),                                  
    T.StructField("search_trends_wart", T.DoubleType(), True),                                  
    T.StructField("search_trends_water_retention", T.DoubleType(), True),                                   
    T.StructField("search_trends_weakness", T.DoubleType(), True),                                  
    T.StructField("search_trends_weight_gain", T.DoubleType(), True),                                   
    T.StructField("search_trends_wheeze", T.DoubleType(), True),                                    
    T.StructField("search_trends_xeroderma", T.DoubleType(), True),                                     
    T.StructField("search_trends_xerostomia", T.DoubleType(), True),                                    
    T.StructField("search_trends_yawn", T.DoubleType(), True),                                  
    T.StructField("new_recovered_age_0", T.LongType(), True),                                   
    T.StructField("new_recovered_age_1", T.LongType(), True),                                   
    T.StructField("new_recovered_age_2", T.LongType(), True),                                   
    T.StructField("new_recovered_age_3", T.LongType(), True),                                   
    T.StructField("new_recovered_age_4", T.LongType(), True),                                   
    T.StructField("new_recovered_age_5", T.LongType(), True),                                   
    T.StructField("new_recovered_age_6", T.LongType(), True),                                   
    T.StructField("new_recovered_age_7", T.LongType(), True),                                   
    T.StructField("new_recovered_age_8", T.LongType(), True),                                   
    T.StructField("new_recovered_age_9", T.LongType(), True),                                   
    T.StructField("cumulative_recovered_age_0", T.LongType(), True),                                    
    T.StructField("cumulative_recovered_age_1", T.LongType(), True),                                    
    T.StructField("cumulative_recovered_age_2", T.LongType(), True),                                    
    T.StructField("cumulative_recovered_age_3", T.LongType(), True),                                    
    T.StructField("cumulative_recovered_age_4", T.LongType(), True),                                    
    T.StructField("cumulative_recovered_age_5", T.LongType(), True),                                    
    T.StructField("cumulative_recovered_age_6", T.LongType(), True),                                    
    T.StructField("cumulative_recovered_age_7", T.LongType(), True),                                    
    T.StructField("cumulative_recovered_age_8", T.LongType(), True),                                    
    T.StructField("cumulative_recovered_age_9", T.LongType(), True),                                    
    T.StructField("new_recovered_male", T.LongType(), True),                                    
    T.StructField("new_recovered_female", T.LongType(), True),                                  
    T.StructField("cumulative_recovered_male", T.LongType(), True),                                     
    T.StructField("cumulative_recovered_female", T.LongType(), True),                                   
    T.StructField("locality_code", T.StringType(), True),                                   
    T.StructField("locality_name", T.StringType(), True),                                   
    T.StructField("new_ventilator_patients", T.LongType(), True),                                   
    T.StructField("cumulative_ventilator_patients", T.LongType(), True),                                    
    T.StructField("new_persons_fully_vaccinated_pfizer", T.LongType(), True),                                   
    T.StructField("cumulative_persons_fully_vaccinated_pfizer", T.LongType(), True),                                    
    T.StructField("new_vaccine_doses_administered_pfizer", T.LongType(), True),                                     
    T.StructField("cumulative_vaccine_doses_administered_pfizer", T.LongType(), True),                                  
    T.StructField("new_persons_fully_vaccinated_moderna", T.LongType(), True),                                  
    T.StructField("cumulative_persons_fully_vaccinated_moderna", T.LongType(), True),                                   
    T.StructField("new_vaccine_doses_administered_moderna", T.LongType(), True),                                    
    T.StructField("cumulative_vaccine_doses_administered_moderna", T.LongType(), True),                                     
    T.StructField("new_persons_fully_vaccinated_janssen", T.LongType(), True),                                  
    T.StructField("cumulative_persons_fully_vaccinated_janssen", T.LongType(), True),                                   
    T.StructField("new_vaccine_doses_administered_janssen", T.LongType(), True),                                    
    T.StructField("cumulative_vaccine_doses_administered_janssen", T.LongType(), True),                                     
    T.StructField("location_geometry", T.StringType(), True)
    ])                                  

# COMMAND ----------

logging.info(f'reading source tables ...')
data = pandas.read_csv(raw_table_path)
df = spark.createDataFrame(data)

bq_df = (spark.read.format("bigquery")
      .option("table",table)
      .option("project_id", project_id)  
      .schema(schema)
      .option('header', 'true')
      .load()
     )
logging.info(f'reading source tables completed {raw_table_path}')

# COMMAND ----------

mobility_df = bq_df.select(
    "date",                      
    "location_key",                      
    "mobility_retail_and_recreation",                        
    "mobility_grocery_and_pharmacy",                     
    "mobility_parks",                        
    "mobility_transit_stations",                     
    "mobility_workplaces",                       
    "mobility_residential"                                           
)
df = df.limit(100)

# COMMAND ----------

    logging.info('started writing...')
    if len(list(filter(lambda x: True if x.name == bronze_table_name else False,spark.catalog.listTables(bronze_database)))) == 0:
        # TABLE DOES NOT EXIST
        logging.info(f'Creating table and saving data to Bronze Layer')
        (df
                .write
                .format('delta')
                .mode('overwrite')
                .option('header', 'true')
                .option('overwriteSchema', 'true')
                .partitionBy(partition_by)
                .option('path', bronze_datalake_location)
                .saveAsTable(f'{bronze_database}.{bronze_table_name}'))
        logging.info(f'finished writing data to Bronze Layer: {bronze_database}.{bronze_table_name}')
    
    else : 
        
        # TABLE EXISTS
        logger.info(f'Merging data to Bronze Layer')
        table = DeltaTable.forName(spark, f"{bronze_database}.{bronze_table_name}")
        (
            table.alias("Hot")
            .merge(
                source = df.alias("New"),
                condition = F.expr(f""" Hot.date = New.date AND 
                                        Hot.location_key = New.location_key """)
            )
            .whenMatchedUpdateAll()
            .whenNotMatchedInsertAll()
        ).execute()
        logging.info(f'Finished merging data to Bronze Layer')

# COMMAND ----------

dbutils.notebook.exit('....')
